name: Build and Deploy

on:
  push:
    branches:
      - gh-pages 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7 

    - name: Install specific Bundler version
      run: gem install bundler

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build Jekyll site
      run: bundle exec jekyll build

    - name: Generate PDF
      run: |
        gem install pdfkit
        sudo apt-get install -y wkhtmltopdf
        bundle exec rake jekyll:generate_pdf

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
