name: Build and Deploy

on:
  push:
    branches:
      - gh-pages 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7.8'

    - name: Install specific Bundler version
      run: gem install bundler -v 2.4.22

    - name: Install dependencies
      run: |
        bundle _2.4.22_ config set path '.vendor/bundle'
        bundle _2.4.22_ install --jobs 4 --retry 3

    - name: Build Jekyll site
      run: bundle _2.4.22_ exec jekyll build

    - name: Generate PDF
      run: |
        gem install pdfkit
        sudo apt-get install -y wkhtmltopdf
        bundle exec rake jekyll:generate_pdf

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
