name: Generate PDF

on:
  push:
    branches:
      - gh-pages  # Change this to your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Pandoc
      run: sudo apt-get install -y pandoc

    - name: Install TeX Live
      run: sudo apt-get install -y texlive-full

    - name: Run PDF generation script
      run: |
        python generate_pdf.py

    - name: Upload PDF
      uses: actions/upload-artifact@v2
      with:
        name: monograph-pdf
        path: output.pdf
