name: Generate PDF

on:
  push:
    branches:
      - main  # Change this to your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Cache Pandoc
      id: cache-pandoc
      uses: actions/cache@v3
      with:
        path: /usr/local/bin/pandoc
        key: ${{ runner.os }}-pandoc

    - name: Install Pandoc
      if: steps.cache-pandoc.outputs.cache-hit != 'true'
      run: sudo apt-get install -y pandoc

    - name: Cache TeX Live
      id: cache-texlive
      uses: actions/cache@v3
      with:
        path: /usr/local/texlive
        key: ${{ runner.os }}-texlive

    - name: Install TeX Live
      if: steps.cache-texlive.outputs.cache-hit != 'true'
      run: sudo apt-get install -y texlive-full

    - name: Run PDF generation script
      run: |
        python generate_pdf.py

    - name: Upload PDF
      uses: actions/upload-artifact@v2
      with:
        name: monograph-pdf
        path: output.pdf
